version: '3'

services:
  mysql:
    image: mysql:5.7.21
    container_name: scpr-mysql
    ports:
      - 3200:3200/tcp
      - 3306:3306/tcp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      scpr-network:
        aliases:
         - mysql

  redis:
    image: redis:4.0.1-alpine
    command: redis-server
    container_name: scpr-redis
    restart: always
    ports:
      - 6379:6379/tcp
    networks:
      scpr-network:
        aliases:
         - redis

  memcached:
    image: memcached:1.5.0-alpine
    command: memcached
    container_name: scpr-memcached
    restart: always
    ports:
      - 11211:11211
    networks:
      scpr-network:
        aliases:
          - memcached

  elasticsearch:
    image: elasticsearch:7.1.0
    container_name: scpr-elasticsearch
    restart: always
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
      - 9250:9250/tcp
    environment:
      "discovery.type": single-node
    volumes:
      - ./esdata:/var/lib/elasticsearch
    networks:
      scpr-network:
        aliases:
         - elasticsearch

volumes:
  scpr-bundle:
  scpr-gems:
  mysql-data:
  elasticsearch-data:

networks:
  scpr-network:

