class SetupElectionDatapoints < ActiveRecord::Migration
  def up
    races = [
      # Title - Key - Value - Notes
      ["Los Angeles Unified School District Member Of The Board Of Education, Board District 1", "", "0", ""],
      ["Long Beach Mayor", "", "0", ""],
      ["LA County Sheriff", "", "0", ""],
      ["LA County Supervisor 3rd District", "", "0", ""],
      ["Secretary Of State", "", "0", ""],
      ["State Of California Attorney General", "", "0", ""],
      ["State Of California Governor", "", "0", ""],
      ["State Of California Insurance Commissioner", "", "0", ""],
      ["State Of California Lieutenant Governor", "", "0", ""],
      ["State Of California Controller", "", "0", ""],
      ["United States Representative 8th District",  "rep:8", "0", ""],
      ["United States Representative 11th District", "rep:11", "0", ""],
      ["United States Representative 23rd District", "rep:23", "0", ""],
      ["United States Representative 24th District", "rep:24", "0", ""],
      ["United States Representative 25th District", "rep:25", "0", ""],
      ["United States Representative 26th District", "rep:26", "0", ""],
      ["United States Representative 27th District", "rep:27", "0", ""],
      ["United States Representative 28th District", "rep:28", "0", ""],
      ["United States Representative 29th District", "rep:29", "0", ""],
      ["United States Representative 30th District", "rep:30", "0", ""],
      ["United States Representative 31st District", "rep:31", "0", ""],
      ["United States Representative 32nd District", "rep:32", "0", ""],
      ["United States Representative 33rd District", "rep:33", "0", ""],
      ["United States Representative 34th District", "rep:34", "0", ""],
      ["United States Representative 35th District", "rep:35", "0", ""],
      ["United States Representative 36th District", "rep:36", "0", ""],
      ["United States Representative 37th District", "rep:37", "0", ""],
      ["United States Representative 38th District", "rep:38", "0", ""],
      ["United States Representative 39th District", "rep:39", "0", ""],
      ["United States Representative 40th District", "rep:40", "0", ""],
      ["United States Representative 41st District", "rep:41", "0", ""],
      ["United States Representative 42nd District", "rep:42", "0", ""],
      ["United States Representative 43rd District", "rep:43", "0", ""],
      ["United States Representative 44th District", "rep:44", "0", ""],
      ["United States Representative 47th District", "rep:47", "0", ""],
      ["United States Representative 50th District", "rep:50", "0", ""],
      ["Member Of The State Assembly 33rd District", "assembly:33", "0", ""],
      ["Member Of The State Assembly 36th District", "assembly:36", "0", ""],
      ["Member Of The State Assembly 37th District", "assembly:37", "0", ""],
      ["Member Of The State Assembly 38th District", "assembly:38", "0", ""],
      ["Member Of The State Assembly 39th District", "assembly:39", "0", ""],
      ["Member Of The State Assembly 40th District", "assembly:40", "0", ""],
      ["Member Of The State Assembly 41st District", "assembly:41", "0", ""],
      ["Member Of The State Assembly 42nd District", "assembly:42", "0", ""],
      ["Member Of The State Assembly 43rd District", "assembly:43", "0", ""],
      ["Member Of The State Assembly 44th District", "assembly:44", "0", ""],
      ["Member Of The State Assembly 45th District", "assembly:45", "0", ""],
      ["Member Of The State Assembly 46th District", "assembly:46", "0", ""],
      ["Member Of The State Assembly 47th District", "assembly:47", "0", ""],
      ["Member Of The State Assembly 48th District", "assembly:48", "0", ""],
      ["Member Of The State Assembly 49th District", "assembly:49", "0", ""],
      ["Member Of The State Assembly 50th District", "assembly:50", "0", ""],
      ["Member Of The State Assembly 51st District", "assembly:51", "0", ""],
      ["Member Of The State Assembly 52nd District", "assembly:52", "0", ""],
      ["Member Of The State Assembly 53rd District", "assembly:53", "0", ""],
      ["Member Of The State Assembly 54th District", "assembly:54", "0", ""],
      ["Member Of The State Assembly 55th District", "assembly:55", "0", ""],
      ["Member Of The State Assembly 56th District", "assembly:56", "0", ""],
      ["Member Of The State Assembly 57th District", "assembly:57", "0", ""],
      ["Member Of The State Assembly 58th District", "assembly:58", "0", ""],
      ["Member Of The State Assembly 59th District", "assembly:59", "0", ""],
      ["Member Of The State Assembly 60th District", "assembly:60", "0", ""],
      ["Member Of The State Assembly 61st District", "assembly:61", "0", ""],
      ["Member Of The State Assembly 62nd District", "assembly:62", "0", ""],
      ["Member Of The State Assembly 63rd District", "assembly:63", "0", ""],
      ["Member Of The State Assembly 64th District", "assembly:64", "0", ""],
      ["Member Of The State Assembly 66th District", "assembly:66", "0", ""],
      ["Member Of The State Assembly 67th District", "assembly:67", "0", ""],
      ["Member Of The State Assembly 70th District", "assembly:70", "0", ""],
      ["Member Of The State Assembly 71st District", "assembly:71", "0", ""],
      ["Member Of The State Assembly 75th District", "assembly:75", "0", ""],
      ["State Senator, 18th District", "senator:18", "0", ""],
      ["State Senator, 20th District", "senator:20", "0", ""],
      ["State Senator, 22nd District", "senator:22", "0", ""],
      ["State Senator, 24th District", "senator:24", "0", ""],
      ["State Senator, 26th District", "senator:26", "0", ""],
      ["State Senator, 28th District", "senator:28", "0", ""],
      ["State Senator, 30th District", "senator:30", "0", ""],
      ["State Senator, 32nd District", "senator:32", "0", ""],
      ["State Senator, 34th District", "senator:34", "0", ""],
      ["Proposition 41", "prop41", "0", ""],
      ["Proposition 42", "prop42", "0", ""]
    ]

    races.each do |race|
      DataPoint.create(title: race[0], data_key: race[1], data_value: race[2], notes: race[3], group_name: "election-june2014")
    end
  end

  def down
    DataPoint.where(group_name: GROUP).destroy_all
  end
end
