class RevokeInactiveAdminUsers < ActiveRecord::Migration
  def up
    usernames = ["aedberg", "aschrank", "amachado", "arinicella", "awilliams", "afalzetta", "alieu", "alloyd", "adomanick", "avasoyan", "aortiz", "acelsi", "aperez", "aaceves", "amturner", "asoleycerro", "bhochberg", "bdelossantos", "bread", "bknotts", "croesler", "crolando", "ckean", "crusso", "chawkins", "cdevall", "cokula", "cpaul", "cdablo", "cwithycombe", "crobinson", "cmoore", "Ccox", "cbrewer", "dcoelho", "dkim", "dlazarus", "dlumb", "denise.guerra", "dtaruc", "drobins", "dfrances", "ejoyce", "echa", "ekidron", "edudley", "efrost", "emutert", "emartinez", "ekang", "ebudrovich", "emcdaniel", "fmolvi", "fng", "Gabrielle", "gcarroll", "gdelvac", "gslater", "hfox", "ibalisy", "interntest", "ilopez", "joclaray", "jmusker", "jfreedman", "jkuo", "jpanetta", "jkandel", "jdodson", "jyen", "jlong", "jharris", "jkagel", "traffic", "jsmith", "jgorin", "jflores", "jarmstrong", "jpatterson", "jguenther", "jgordon", "jbenn", "jserviss", "jomartinez", "jjimenez", "jberman", "Juana", "jallen", "jsmall", "jwestfall", "jcruz", "jball", "kfunaro", "kfritsche", "kmoran", "kkellman", "kbutler", "kdavis", "kmiles", "kschwartz", "KMcCormack", "kchen", "kscarboro", "klloyd", "kbui", "volunteer2", "kpccint1", "volunteer", "Kjae", "lkrantz", "lrainey", "lotheningirard", "lanwar", "lbenson", "lgomez", "myasuda", "madhusrikantha", "mclark", "mlouie", "mmacleod", "mlacter", "mathomas", "mschevker", "mburke", "mcrotty", "MattLee", "mjuliano", "mgray", "mthorpe", "mluhar", "mmohan", "nadams", "nyemenidjian", "ntavidian", "nerinakis", "nconti", "nalteir", "oshamout", "Pyu", "volunteer3", "pnazario", "pambrose", "qkim", "qlovrich", "rmanavalan", "rbecker", "rhill", "rgarrova", "rguerra", "rrudick", "rstanton", "rguidi", "rfonseca", "skhan", "sblum", "sschaefer", "sample", "smarshall", "ssweeney", "bricker-test", "sfahey", "ssterling", "skhalifian", "smeraji", "sju", "sdeleontzic", "shochman", "scuevas", "svalot", "tjohnson", "tmiller", "trobbins", "trosales", "test", "tannick", "todd.johnson", "tlewis", "tlimon", "wlee", "billcelis"]

    usernames.each do |username|
      AdminUser.where(username: username).update_all(can_login: 0)
      say "Revoking login access for: #{username}"
    end

  end

  def down
    usernames = ["aedberg", "aschrank", "amachado", "arinicella", "awilliams", "afalzetta", "alieu", "alloyd", "adomanick", "avasoyan", "aortiz", "acelsi", "aperez", "aaceves", "amturner", "asoleycerro", "bhochberg", "bdelossantos", "bread", "bknotts", "croesler", "crolando", "ckean", "crusso", "chawkins", "cdevall", "cokula", "cpaul", "cdablo", "cwithycombe", "crobinson", "cmoore", "Ccox", "cbrewer", "dcoelho", "dkim", "dlazarus", "dlumb", "denise.guerra", "dtaruc", "drobins", "dfrances", "ejoyce", "echa", "ekidron", "edudley", "efrost", "emutert", "emartinez", "ekang", "ebudrovich", "emcdaniel", "fmolvi", "fng", "Gabrielle", "gcarroll", "gdelvac", "gslater", "hfox", "ibalisy", "interntest", "ilopez", "joclaray", "jmusker", "jfreedman", "jkuo", "jpanetta", "jkandel", "jdodson", "jyen", "jlong", "jharris", "jkagel", "traffic", "jsmith", "jgorin", "jflores", "jarmstrong", "jpatterson", "jguenther", "jgordon", "jbenn", "jserviss", "jomartinez", "jjimenez", "jberman", "Juana", "jallen", "jsmall", "jwestfall", "jcruz", "jball", "kfunaro", "kfritsche", "kmoran", "kkellman", "kbutler", "kdavis", "kmiles", "kschwartz", "KMcCormack", "kchen", "kscarboro", "klloyd", "kbui", "volunteer2", "kpccint1", "volunteer", "Kjae", "lkrantz", "lrainey", "lotheningirard", "lanwar", "lbenson", "lgomez", "myasuda", "madhusrikantha", "mclark", "mlouie", "mmacleod", "mlacter", "mathomas", "mschevker", "mburke", "mcrotty", "MattLee", "mjuliano", "mgray", "mthorpe", "mluhar", "mmohan", "nadams", "nyemenidjian", "ntavidian", "nerinakis", "nconti", "nalteir", "oshamout", "Pyu", "volunteer3", "pnazario", "pambrose", "qkim", "qlovrich", "rmanavalan", "rbecker", "rhill", "rgarrova", "rguerra", "rrudick", "rstanton", "rguidi", "rfonseca", "skhan", "sblum", "sschaefer", "sample", "smarshall", "ssweeney", "bricker-test", "sfahey", "ssterling", "skhalifian", "smeraji", "sju", "sdeleontzic", "shochman", "scuevas", "svalot", "tjohnson", "tmiller", "trobbins", "trosales", "test", "tannick", "todd.johnson", "tlewis", "tlimon", "wlee", "billcelis"]

    usernames.each do |username|
      AdminUser.where(username: username).update_all(can_login: 1)
      say "Granting login access for: #{username}"
    end
  end
end
